settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 0
  host: ""
schema:
- name: hello-golang
  path: /Users/shuji/Documents/github.com/shuji-koike/hello-golang
  commands:
    vet:
      status: true
    fmt:
      status: true
    build:
      status: true
    run:
      status: true
  watcher:
    paths: []
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
